version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    # volumes:
    #   - ./static:/app/staticfiles for production
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres_data:
# for production add to command instead of "python manage.py runserver" --> "gunicorn xlimport.wsgi:application --bind 0.0.0.0:8000"
